=== anup0206/code/webtech/exam question/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Butwal">
        <xs:complexType>
            <xs:sequence>   
                <xs:element name="employee">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:string"/>
                            
                            <xs:element name="username">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="8"/>
                                        <xs:maxLength value="12"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="post">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="5"/>
                                        <xs:maxLength value="8"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="salary">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="25000"/>
                                        <xs:maxInclusive value="50000"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="gender">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Male"/>
                                        <xs:enumeration value="Female"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <xs:element name="address">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="temporary" type="xs:string"/>
                                        <xs:element name="permanent" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="password">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="6"/>
                                        <xs:maxLength value="15"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== anup0206/code/webtech/exam question/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<Butwal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
  <employee>
    <username>Anupam123</username>
    <post>Chairman</post>
    <salary>50000</salary>
    <gender>Male</gender>
    <address>  
      <temporary>Butwal</temporary>
      <permanent>Sunwal</permanent>
    </address>
    <password>p@ssw0rd</password>
  </employee>
  <ID>12345</ID>
</Butwal>
